version: '3.3'

volumes:
  pg_data:
  redis_data:
  static:

services:
  db:
    image: postgres:alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    command: redis-server --requirepass $REDIS_PASSWORD
    env_file: .env
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data

  backend:
    depends_on:
      - db
      - redis
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - static:/backend_static
    env_file: .env

  gateway:
    build: ./gateway/
    volumes:
      - static:/static/
    ports:
      - 8000:80