version: '3.3'

volumes:
  pg_data:
  redis_data:

services:

  db:
    image: postgres:alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    command: redis-server --requirepass $REDIS_PASSWORD
    env_file: .env
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data