# Generated by Django 4.2.11 on 2024-04-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='invite_code',
            field=models.CharField(default='3Io8cBM', editable=False, max_length=6, unique=True, verbose_name='Инвайт-код для приглашения'),
        ),
    ]
