# Generated by Django 4.2.11 on 2024-04-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='invite_code',
            field=models.CharField(default='4rLsTpo', editable=False, max_length=6, unique=True, verbose_name='Инвайт-код для приглашения'),
        ),
    ]
